### ISSUE TITLE
Seed isn't working

### ISSUE THREAD

**Issue by custompro12** [Nick088Official/SuperPrompt-v1#3]
Passing in a value of `0` to try to use a random seed still gives the same output prompt for any given input prompt.

Command used:
```bash
python Scripts/install_and_run_no_ui.py "a big black cat" 512 1.2 0.5 'fp16' 1 1 0
```

**Comment by Nick088Official** [comment]
Hey, i looked into this, and now it uses the seed correctly, also, you need to put an higher top p like 0.95, an higher top k like 50, and an higher temperature like 0.7 (as an example). I also added a task prefix parameter that you can change which is basically the prompt to the ai on how to expand your prompt. Also if you want there's a no ui bat file to run it instead of doing it manually with the command in cmd
